# Generated by Django 5.1.2 on 2024-10-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_order_address_order_grand_total_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Confirmed', 'Confirmed'), ('Transmitted', 'Transmitted'), ('Delivered', 'DELIVERED'), ('Cancelled', 'Cancelled')], default='Placed', max_length=20),
        ),
    ]
